// atomic/templates/entity-datatable-card/index.tsx
'use client'

import type { DataTableFilterMeta } from 'primereact/datatable'
import { Skeleton } from 'primereact/skeleton'
import React, { useMemo, useState } from 'react'
import { useTranslation } from 'react-i18next'

import type { NucEntityDatatableCardInterface } from 'nucleify'
import {
  AdButton,
  AdCard,
  AdHeading,
  columns,
  NucEntityDataTable,
  NucShareDialog,
} from 'nucleify'

import './_index.scss'

export const NucEntityDataTableCard: React.FC<
  NucEntityDatatableCardInterface
> = (props) => {
  const { t } = useTranslation()

  const [shareDialogVisible, setShareDialogVisible] = useState(false)
  const [selectedItems, setSelectedItems] = useState<unknown[]>([])
  type ColumnWithField = { field?: string }

  const specificColumns = useMemo(() => {
    return columns[props.adType as keyof typeof columns] || []
  }, [props.adType])

  const globalFilterFields = useMemo(() => {
    return specificColumns
      .map((col: ColumnWithField) => col.field)
      .filter((field: string | undefined): field is string => Boolean(field))
  }, [specificColumns])

  const disabledShareTypes = [
    'activity',
    'user',
    'card',
    'question',
    'link',
    'feature',
    'technology',
  ]

  const shareEnabled = useMemo(() => {
    return !disabledShareTypes.includes(props.adType as string)
  }, [props.adType])

  const [filters, setFilters] = useState(() => {
    const initialFilters: DataTableFilterMeta = {
      global: { value: '', matchMode: 'contains' },
    }
    specificColumns.forEach((col: ColumnWithField) => {
      if (col.field) {
        initialFilters[col.field] = { value: null, matchMode: 'contains' }
      }
    })
    return initialFilters
  })

  const headerTemplate = (
    <div className="nuc-entity-datatable-card-header-container">
      {props.loading ? (
        <>
          <Skeleton
            width="180px"
            height="32px"
            borderRadius="10px"
            className="heading-skeleton"
          />
          <div className="heading-actions-skeleton">
            {shareEnabled && (
              <Skeleton width="42px" height="42px" shape="circle" />
            )}
            <Skeleton width="42px" height="42px" shape="circle" />
          </div>
        </>
      ) : (
        <>
          <AdHeading tag={props.tag ?? 3} text={props.headerText} />

          <div className="nuc-entity-datatable-card-header-actions">
            {props.adType !== 'activity' && (
              <AdButton
                adType={props.adType as AdTypeType}
                icon="prime:share-alt"
                rounded
                text
                onClick={() => setShareDialogVisible(true)}
              />
            )}
            {props.adType !== 'activity' && (
              <AdButton
                adType={props.adType as AdTypeType}
                icon="prime:plus"
                rounded
                text
                onClick={() => props.openDialog?.('create')}
              />
            )}
          </div>
        </>
      )}
    </div>
  )

  return (
    <>
      <AdCard className="nuc-entity-datatable-card" title={headerTemplate}>
        {props.value && (
          <NucEntityDataTable
            value={props.value}
            rows={10}
            rowsPerPageOptions={[10, 20, 50]}
            openDialog={props.openDialog}
            adType={props.adType}
            loading={props.loading}
            globalFilterFields={globalFilterFields}
            enableShare={shareEnabled}
            filters={filters}
            onFiltersUpdate={setFilters}
            filterDisplay="row"
            paginatorTemplate="FirstPageLink PrevPageLink CurrentPageReport NextPageLink LastPageLink RowsPerPageDropdown"
            currentPageReportTemplate={t('datatable-paginator', {
              first: '{first}',
              last: '{last}',
              totalRecords: '{totalRecords}',
            })}
            onSelectedUpdate={setSelectedItems}
          />
        )}
      </AdCard>

      <NucShareDialog
        visible={shareDialogVisible}
        onUpdateVisible={(val) => setShareDialogVisible(val)}
        adType={props.adType as ObjectNameType}
        selectedEntities={selectedItems}
      />
    </>
  )
}

// atomic/templates/entity-datatable-card/index.vue
<template>
  <ad-card class="nuc-entity-datatable-card">
    <template #title>
      <div class="nuc-entity-datatable-card-header-container">
        <template v-if="props.loading">
          <ad-skeleton
            :loading="props.loading"
            width="180px"
            height="32px"
            border-radius="10px"
            class="heading-skeleton"
          />
          <div class="heading-actions-skeleton">
            <ad-skeleton
              v-if="shareEnabled"
              :loading="props.loading"
              width="42px"
              height="42px"
              shape="circle"
            />
            <ad-skeleton
              :loading="props.loading"
              width="42px"
              height="42px"
              shape="circle"
            />
          </div>
        </template>
        <template v-else>
          <ad-heading :tag="props.tag" :text="props.headerText" />

          <div class="nuc-entity-datatable-card-header-actions">
            <ad-button
              v-if="props.adType !== 'activity'"
              :ad-type="props.adType"
              icon="prime:share-alt"
              rounded
              text
              @click="shareDialogVisible = true"
            />
            <ad-button
              v-if="props.adType !== 'activity'"
              :ad-type="props.adType"
              icon="prime:plus"
              rounded
              text
              @click="props.openDialog?.('create')"
            />
          </div>
        </template>
      </div>
    </template>
    <template #content>
      <nuc-entity-datatable
        v-if="props.value"
        :value="props.value"
        :rows="10"
        :rows-per-page-options="[10, 20, 50]"
        :open-dialog="props.openDialog"
        :ad-type="props.adType"
        :loading="props.loading"
        :global-filter-fields="globalFilterFields"
        :enable-share="shareEnabled"
        v-model:filters="filters"
        filter-display="row"
        paginator-template="FirstPageLink PrevPageLink CurrentPageReport NextPageLink LastPageLink RowsPerPageDropdown"
        :current-page-report-template="t('datatable-paginator', { first: '{first}', last: '{last}', totalRecords: '{totalRecords}' })"
        @update:selected="selectedItems = $event"
      />
    </template>
  </ad-card>

  <nuc-share-dialog
    v-model:visible="shareDialogVisible"
    :ad-type="props.adType"
    :selected-entities="selectedItems"
  />
</template>

<script setup lang="ts">
import { computed, ref } from 'vue'
import { useI18n } from 'vue-i18n'

import type { NucEntityDatatableCardInterface } from 'nucleify'
import { columns } from 'nucleify'

const { t } = useI18n()

const props = defineProps<NucEntityDatatableCardInterface>()

const shareDialogVisible = ref(false)
const selectedItems = ref<unknown[]>([])

const specificColumns = columns[props.adType as keyof typeof columns]

const filters = ref({
  global: { value: '', matchMode: 'contains' },
  ...Object.fromEntries(
    specificColumns.map((col: { field?: string }) => [
      col.field,
      { value: null, matchMode: 'contains' },
    ])
  ),
})

const globalFilterFields = computed(() =>
  specificColumns.map((col: { field?: string }) => col.field).filter(Boolean)
)

const disabledShareTypes = [
  'activity',
  'user',
  'card',
  'question',
  'link',
  'feature',
  'technology',
]
const shareEnabled = computed(
  () => !disabledShareTypes.includes(props.adType as string)
)
</script>

<style lang="scss">
@import 'index';
</style>
