// atomic/templates/entity-datatable-skeleton/index.tsx
import { Column } from 'primereact/column'
import { Skeleton } from 'primereact/skeleton'
import React from 'react'

import type { NucSkeletonDataTableInterface } from 'nucleify'
import { AdDataTable } from 'nucleify'

export const NucEntityDataTableSkeleton: React.FC<
  NucSkeletonDataTableInterface
> = ({ adType, loading, rows, enableShare, specificColumns }) => {
  if (!loading) return null
  const tableRows = rows.map((_, index) => ({ id: index }))

  const shareHeaderTemplate = () => <Skeleton width="24px" height="24px" />
  const shareBodyTemplate = () => <Skeleton width="24px" height="24px" />

  const dynamicHeaderTemplate = () => <Skeleton width="100%" height="22px" />
  const dynamicFilterTemplate = () => <Skeleton width="100%" height="22px" />
  const dynamicBodyTemplate = () => <Skeleton height="34px" />

  const actionBodyTemplate = () => (
    <div className="action-column-content">
      {[1, 2, 3].map((index) => (
        <Skeleton
          key={index}
          className="desktop"
          shape="circle"
          width="34px"
          height="34px"
        />
      ))}

      <Skeleton className="mobile" shape="circle" width="34px" height="34px" />
    </div>
  )

  return (
    <AdDataTable
      adType={adType as ObjectNameType}
      value={tableRows}
      size="small"
      filterDisplay="row"
      className="entity-datatable skeleton-data-table"
    >
      {enableShare && (
        <Column
          className="share-checkbox-column"
          headerClassName="share-checkbox-column"
          header={shareHeaderTemplate}
          body={shareBodyTemplate}
        />
      )}

      {specificColumns?.map((col, index) => (
        <Column
          key={index}
          className={col.class}
          headerClassName={col.class}
          header={dynamicHeaderTemplate}
          filter
          filterElement={dynamicFilterTemplate}
          showFilterMenu={false}
          body={dynamicBodyTemplate}
        />
      ))}

      <Column
        className="action-column"
        headerClassName="action-column"
        body={actionBodyTemplate}
      />
    </AdDataTable>
  )
}

// atomic/templates/entity-datatable-skeleton/index.vue
<template>
  <ad-data-table
    v-if="props.loading"
    :ad-type="props.adType"
    :value="props.rows"
    size="small"
    filter-display="row"
    class="entity-datatable skeleton-data-table"
  >
    <Column v-if="props.enableShare" class="share-checkbox-column">
      <template #header>
        <ad-skeleton :loading="props.loading" width="24px" height="24px" />
      </template>
      <template #body>
        <ad-skeleton :loading="props.loading" width="24px" height="24px" />
      </template>
    </Column>
    <Column
      v-for="(col, index) in props.specificColumns"
      :key="index"
      :class="col.class"
    >
      <template #header>
        <ad-skeleton :loading="props.loading" width="100%" height="22px" />
      </template>
      <template #filter>
        <ad-skeleton :loading="props.loading" width="100%" height="22px" />
      </template>
      <template #body>
        <ad-skeleton :loading="props.loading" height="34px" />
      </template>
    </Column>
    <Column class="action-column">
      <template #body>
        <div class="action-column-content">
          <ad-skeleton
            v-for="index in 3"
            :key="index"
            :loading="props.loading"
            class="desktop"
            shape="circle"
            width="34px"
            height="34px"
          />
          <ad-skeleton
            :loading="props.loading"
            class="mobile"
            shape="circle"
            width="34px"
            height="34px"
          />
        </div>
      </template>
    </Column>
  </ad-data-table>
</template>

<script setup lang="ts">
import type { NucSkeletonDataTableInterface } from 'nucleify'

const props = defineProps<NucSkeletonDataTableInterface>()
</script>
