// atomic/templates/entity-datatable/index.tsx
'use client'

import { Column, ColumnFilterElementTemplateOptions } from 'primereact/column'
import type {
  DataTableFilterEvent,
  DataTableFilterMeta,
  DataTableRowClickEvent,
} from 'primereact/datatable'
import { Menu } from 'primereact/menu'
import React, { useCallback, useEffect, useMemo, useRef } from 'react'
import { useTranslation } from 'react-i18next'

import type { ColumnInterface, NucEntityDatatableInterface } from 'nucleify'
import {
  AdButton,
  AdDataTable,
  AdInputText,
  AdMenu,
  actions as actionsList,
  columns,
  NucEntityDataTableSkeleton,
  NucShareCheckbox,
  type OpenDialogFunctionType,
  useMenu,
  useSelect,
  useShareSelection,
} from 'nucleify'

import './_index.scss'

type TableRowData = Record<string, unknown> & { id: number }
type ShareTableRow = TableRowData & { __shareChecked: boolean }

const toRowData = (row: ShareTableRow): TableRowData => {
  const { __shareChecked: _checked, ...data } = row
  return data as TableRowData
}

interface ActionItem {
  icon: string
  click: (data: TableRowData) => void
}

interface NucEntityDataTableProps extends NucEntityDatatableInterface {
  onFiltersUpdate?: (filters: DataTableFilterMeta) => void
  onSelectedUpdate?: (selected: unknown[]) => void
}

export const NucEntityDataTable: React.FC<NucEntityDataTableProps> = (
  props
) => {
  const { t } = useTranslation()

  const {
    adType,
    value,
    openDialog,
    enableShare,
    filters,
    rows = 10,
    loading,
    onFiltersUpdate,
    onSelectedUpdate,
    selection: _selection,

    actions: propsActions,
    selectedObject: propsSelectedObject,

    ...restProps
  } = props

  const menuRef = useRef<Menu>(null)

  const fallbackOpenDialog: OpenDialogFunctionType = useCallback(
    () => undefined,
    []
  )
  const resolvedOpenDialog = useMemo<OpenDialogFunctionType>(
    () => openDialog ?? fallbackOpenDialog,
    [openDialog, fallbackOpenDialog]
  )

  const actions = useMemo(
    () => actionsList(resolvedOpenDialog),
    [resolvedOpenDialog]
  )

  const { openMenu, selectedObject } = useMenu()

  const { selectItems } = useSelect(selectedObject, resolvedOpenDialog)

  const specificColumns = useMemo<readonly ColumnInterface[]>(() => {
    return columns[adType as keyof typeof columns] || []
  }, [adType])

  const skeletonRows = useMemo(() => Array.from({ length: rows }), [rows])

  const items = (value as TableRowData[]) || undefined

  const {
    selected,
    isAllSelected,
    isIndeterminate,
    toggle,
    toggleAll,
    getSelectedItems,
  } = useShareSelection(items)

  // PrimeReact nie re-renderuje body kolumny przy zmianie zewnętrznego stanu
  // (w przeciwieństwie do reaktywnego slotu w PrimeVue). Wpinamy zaznaczenie w value.
  const tableRows = useMemo<ShareTableRow[]>(() => {
    if (!items?.length) return []

    return items.map((item) => ({
      ...item,
      __shareChecked: selected[item.id] === true,
    }))
  }, [items, selected])

  useEffect(() => {
    onSelectedUpdate?.(getSelectedItems<TableRowData>())
  }, [selected, onSelectedUpdate, getSelectedItems])

  const shareHeaderTemplate = () => (
    <NucShareCheckbox
      key={`share-all-${isAllSelected}-${isIndeterminate}`}
      adType={adType as AdTypeType}
      checked={isAllSelected}
      indeterminate={isIndeterminate}
      isAll
      onToggle={toggleAll}
    />
  )

  const shareBodyTemplate = (rowData: ShareTableRow) => (
    <NucShareCheckbox
      adType={adType as AdTypeType}
      checked={rowData.__shareChecked}
      onToggle={() => toggle(rowData.id)}
    />
  )

  const filterTemplate = (
    options: ColumnFilterElementTemplateOptions,
    colHeader: string
  ) => (
    <AdInputText
      className="entity-datatable-filter-input"
      adType={adType}
      value={(options.value as string) || ''}
      placeholder={t('column-search-placeholder', { column: t(colHeader) })}
      onChange={(e) => options.filterApplyCallback(e.target.value)}
    />
  )

  const actionBodyTemplate = (rowData: ShareTableRow) => (
    <div className="action-column-content">
      {adType === 'activity' ? (
        <AdButton
          adType={adType as AdTypeType}
          variant="data-table"
          icon="prime:trash"
          rounded
          text
          loading={!!loading}
          onClick={(event) => {
            event.stopPropagation()
            openDialog?.('delete', toRowData(rowData))
          }}
        />
      ) : (
        <>
          {actions.map((action: ActionItem) => (
            <AdButton
              key={action.icon}
              adType={adType as AdTypeType}
              media="desktop"
              variant="data-table"
              icon={action.icon}
              rounded
              text
              loading={!!loading}
              onClick={(event) => {
                event.stopPropagation()
                action.click(toRowData(rowData))
              }}
            />
          ))}
          <AdButton
            adType={adType as AdTypeType}
            media="mobile"
            variant="data-table"
            icon="prime:bars"
            rounded
            text
            loading={!!loading}
            onClick={(event) => {
              event.stopPropagation()
              openMenu(menuRef.current, event, toRowData(rowData))
            }}
          />
          <AdMenu ref={menuRef} model={selectItems} />
        </>
      )}
    </div>
  )

  return (
    <>
      {!loading ? (
        <AdDataTable
          adType={adType}
          className="entity-datatable"
          dataKey="id"
          value={tableRows}
          rows={rows}
          paginator={restProps.paginator ?? true}
          filters={filters as DataTableFilterMeta}
          onFilter={(e: DataTableFilterEvent) => onFiltersUpdate?.(e.filters)}
          onRowClick={(e: DataTableRowClickEvent) =>
            openDialog?.('show', toRowData(e.data as ShareTableRow))
          }
          {...restProps}
          stripedRows={false}
          rowHover={false}
        >
          {enableShare && (
            <Column
              className="share-checkbox-column"
              headerClassName="share-checkbox-column"
              header={shareHeaderTemplate}
              body={shareBodyTemplate}
            />
          )}

          {specificColumns.map((col, index) => (
            <Column
              key={col.field ?? `${adType}-col-${index}`}
              field={col.field}
              header={t(col.header ?? '')}
              className={col.class}
              headerClassName={col.class}
              sortable={col.sortable}
              filter
              filterMatchMode="contains"
              filterElement={(options) =>
                filterTemplate(options, col.header ?? '')
              }
            />
          ))}

          <Column
            className="action-column"
            headerClassName="action-column"
            body={actionBodyTemplate}
          />
        </AdDataTable>
      ) : null}

      <NucEntityDataTableSkeleton
        adType={adType as string}
        enableShare={enableShare}
        rows={skeletonRows}
        loading={loading ?? false}
        specificColumns={[...specificColumns]}
      />
    </>
  )
}

// atomic/templates/entity-datatable/index.vue
<template>
  <ad-data-table
    :ad-type="props.adType"
    :value="props.value"
    :data-key="props.dataKey"
    :rows="props.rows"
    :first="props.first"
    :total-records="props.totalRecords"
    :paginator="props.paginator"
    :paginator-position="props.paginatorPosition"
    :always-show-paginator="props.alwaysShowPaginator"
    :paginator-template="props.paginatorTemplate"
    :page-link-size="props.pageLinkSize"
    :rows-per-page-options="props.rowsPerPageOptions"
    :current-page-report-template="props.currentPageReportTemplate"
    :lazy="props.lazy"
    :loading="props.loading"
    :loading-icon="props.loadingIcon"
    :sort-field="props.sortField"
    :sort-order="props.sortOrder"
    :null-sort-order="props.nullSortOrder"
    :default-sort-order="props.defaultSortOrder"
    :multi-sort-meta="props.multiSortMeta"
    :sort-mode="props.sortMode"
    :removable-sort="props.removableSort"
    :filter-display="props.filterDisplay || 'row'"
    :filter-locale="props.filterLocale"
    :selection-mode="props.selectionMode"
    :compare-selection-by="props.compareSelectionBy"
    :meta-key-selection="props.metaKeySelection"
    :context-menu="props.contextMenu"
    :context-menu-selection="props.contextMenuSelection"
    :select-all="props.selectAll"
    :row-hover="props.rowHover"
    :csv-separator="props.csvSeparator"
    :export-filename="props.exportFilename"
    :export-function="props.exportFunction"
    :resizable-columns="props.resizableColumns"
    :column-resize-mode="props.columnResizeMode"
    :reorderable-columns="props.reorderableColumns"
    :expanded-rows="props.expandedRows"
    :expanded-row-icon="props.expandedRowIcon"
    :collapsed-row-icon="props.collapsedRowIcon"
    :row-group-mode="props.rowGroupMode"
    :group-rows-by="props.groupRowsBy"
    :expandable-row-groups="props.expandableRowGroups"
    :expanded-row-groups="props.expandedRowGroups"
    :state-storage="props.stateStorage"
    :state-key="props.stateKey"
    :edit-mode="props.editMode"
    :editing-rows="props.editingRows"
    :row-class="props.rowClass"
    :row-style="props.rowStyle"
    :scrollable="props.scrollable"
    :scroll-height="props.scrollHeight"
    :virtual-scroller-options="props.virtualScrollerOptions"
    :frozen-value="props.frozenValue"
    :breakpoint="props.breakpoint"
    :show-headers="props.showHeaders"
    :show-gridlines="props.showGridlines"
    :striped-rows="props.stripedRows"
    :highlight-on-select="props.highlightOnSelect"
    :size="props.size"
    :table-style="props.tableStyle"
    :table-class="props.tableClass"
    :table-props="props.tableProps"
    :filter-input-props="props.filterInputProps"
    :filter-button-props="{
      filter: { 
        pt: { 
          root: { 
            'ad-type': props.adType 
          } 
        } 
      }
    }"
    :edit-button-props="props.editButtonProps"
    :dt="props.dt"
    :pt="props.pt"
    :pt-options="props.ptOptions"
    :unstyled="props.unstyled"
    :open-dialog="props.openDialog"
    :selected-object="props.selectedObject"
    v-model:filters="props.filters"
    @update:filters="emits('update:filters', $event)"
    @row-click="props.openDialog?.('show', $event.data)"
    class="entity-datatable"
  >
    <Column v-if="shareEnabled" class="share-checkbox-column">
      <template #header>
        <nuc-share-checkbox
          :ad-type="props.adType"
          :checked="isAllSelected"
          :indeterminate="isIndeterminate"
          :is-all="true"
          @toggle="toggleAll"
        />
      </template>
      <template #body="{ data }">
        <nuc-share-checkbox
          :ad-type="props.adType"
          :checked="selected[data.id]"
          @toggle="toggle(data.id)"
        />
      </template>
    </Column>
    <Column
      v-for="col in specificColumns"
      :key="col.field"
      :field="col.field"
      :header="t(col.header)"
      :class="col.class"
      :sortable="col.sortable"
      :filter="true"
      filterMatchMode="contains"
    >
      <template #filter="{ filterModel, filterCallback }">
        <ad-input-text
          v-model="filterModel.value"
          :value="filterModel.value || ''"
          :placeholder="t('column-search-placeholder', { column: t(col.header) })"
          :ad-type="props.adType"
          @input="filterCallback()"
        />
      </template>
    </Column>
    <Column class="action-column">
      <template #body="row">
        <div class="action-column-content">
          <ad-button
            v-if="props.adType === 'activity'"
            :ad-type="props.adType"
            class="data-table-button"
            icon="prime:trash"
            rounded
            text
            :loading="props.loading"
            @click="openDialog!('delete', row.data)"
          />
          <template v-else>
            <ad-button
              v-for="action in actions"
              :key="action.icon"
              :ad-type="props.adType"
              media="desktop"
              variant="data-table"
              :icon="action.icon"
              rounded
              text
              :loading="props.loading"
              @click="action.click(row.data)"
            />
            <ad-button
              :ad-type="props.adType"
              media="mobile"
              variant="data-table"
              icon="prime:bars"
              rounded
              text
              :loading="props.loading"
              @click="openMenu(menu, $event, row.data)"
            />
            <ad-menu ref="menu" :model="selectItems" :popup="true" />
          </template>
        </div>
      </template>
    </Column>
  </ad-data-table>

  <nuc-entity-datatable-skeleton
    :enable-share="shareEnabled"
    :rows="skeleton"
    :loading="props.loading"
    :specific-columns="specificColumns"
  />
</template>

<script setup lang="ts">
import { useI18n } from 'vue-i18n'

import type { NucEntityDatatableInterface } from 'nucleify'
import {
  actions as actionsList,
  columns,
  useMenu,
  useSelect,
  useShareSelection,
} from 'nucleify'

const { t } = useI18n()

const props = defineProps<NucEntityDatatableInterface>()
const emits = defineEmits(['update:filters', 'update:selected'])

const menu = ref()
const actions = actionsList(props.openDialog!)

const { openMenu, selectedObject } = useMenu()
const { selectItems } = useSelect(selectedObject, props.openDialog!)

const specificColumns = columns[props.adType as keyof typeof columns]
const skeleton = ref(new Array(props.rows))

const shareEnabled = computed(() => props.enableShare)

const items = computed(() => props.value as { id: number }[] | undefined)
const {
  selected,
  isAllSelected,
  isIndeterminate,
  toggle,
  toggleAll,
  getSelectedItems,
} = useShareSelection(items)

watch(
  selected,
  () => {
    emits('update:selected', getSelectedItems())
  },
  { deep: true }
)
</script>

<style lang="scss" scoped>
@import 'index';
</style>
